// <auto-generated />
using System;
using InvoiceReviewAssistant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceReviewAssistant.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InvoiceDbContext))]
    partial class InvoiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DraftVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId", "OccurredAtUtc", "Id");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.FieldCorrectionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuditEventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DraftVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuditEventId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("FieldCorrections", (string)null);
                });

            modelBuilder.Entity("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.InvoiceDocumentEntity", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IntegrityStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceId");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("InvoiceDocuments", (string)null);
                });

            modelBuilder.Entity("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.InvoiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentValidationRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionKind")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentTextSource")
                        .HasColumnType("TEXT");

                    b.Property<int>("DraftVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastValidatedVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedInvoiceNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NormalizedPaymentTermsDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedSupplierName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessingFailedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessingFailureCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessingFailureMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessingFailureStage")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierRegistrationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Total")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc")
                        .IsDescending();

                    b.HasIndex("NormalizedSupplierName", "NormalizedInvoiceNumber");

                    b.HasIndex("Status", "UpdatedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.InvoiceFieldMetadataEntity", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldKey")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("CurrentSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCorrectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceId", "FieldKey");

                    b.ToTable("InvoiceFieldMetadata", (string)null);
                });

            modelBuilder.Entity("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.ValidationResultEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedFieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ValidationRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ValidationRunId");

                    b.ToTable("ValidationResults", (string)null);
                });

            modelBuilder.Entity("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.ValidationRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DraftVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId", "ValidatedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("ValidationRuns", (string)null);
                });

            modelBuilder.Entity("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.HasOne("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.InvoiceEntity", "Invoice")
                        .WithMany("AuditEvents")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.FieldCorrectionEntity", b =>
                {
                    b.HasOne("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.AuditEventEntity", "AuditEvent")
                        .WithMany("FieldCorrections")
                        .HasForeignKey("AuditEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.InvoiceEntity", "Invoice")
                        .WithMany("FieldCorrections")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditEvent");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.InvoiceDocumentEntity", b =>
                {
                    b.HasOne("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.InvoiceEntity", "Invoice")
                        .WithOne("Document")
                        .HasForeignKey("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.InvoiceDocumentEntity", "InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.InvoiceFieldMetadataEntity", b =>
                {
                    b.HasOne("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.InvoiceEntity", "Invoice")
                        .WithMany("FieldMetadata")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.ValidationResultEntity", b =>
                {
                    b.HasOne("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.ValidationRunEntity", "ValidationRun")
                        .WithMany("Results")
                        .HasForeignKey("ValidationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ValidationRun");
                });

            modelBuilder.Entity("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.ValidationRunEntity", b =>
                {
                    b.HasOne("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.InvoiceEntity", "Invoice")
                        .WithMany("ValidationRuns")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Navigation("FieldCorrections");
                });

            modelBuilder.Entity("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.InvoiceEntity", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("Document");

                    b.Navigation("FieldCorrections");

                    b.Navigation("FieldMetadata");

                    b.Navigation("ValidationRuns");
                });

            modelBuilder.Entity("InvoiceReviewAssistant.Infrastructure.Persistence.Entities.ValidationRunEntity", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
