<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>InvoiceReviewAssistant.IntegrationTests</AssemblyName>
    <RootNamespace>InvoiceReviewAssistant.IntegrationTests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\InvoiceReviewAssistant.Api\InvoiceReviewAssistant.Api.csproj" />
    <ProjectReference Include="..\..\src\InvoiceReviewAssistant.Infrastructure\InvoiceReviewAssistant.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
</Project>
